# File: infrastructure/docker/docker-compose.devops.override.yml
services:
  backend:
    volumes:
      # Override original volumes to mount the entire project workspace
      - ../..:/workspace
    working_dir: /workspace
