"""Create initial schema and hypertable for TimescaleDB

Revision ID: 0001_init_timescale
Revises:
Create Date: 2025-10-20 10:31:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_init_timescale"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ("timescale",)  # Branch label
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_metrics",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),  # FK removed
        sa.Column("metric_name", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        # NOTE: The ForeignKeyConstraint to 'devices.id' has been removed.
        # You cannot create a foreign key between two separate databases.
        # This relationship must be handled at the application layer.
        sa.PrimaryKeyConstraint("time", "device_id", "metric_name"),
    )
    op.execute("SELECT create_hypertable('device_metrics', 'time');")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Dropping the table also drops the hypertable
    op.drop_table("device_metrics")
    # We generally don't drop the extension during a downgrade
    # ### end Alembic commands ###
