# .github/workflows/test_discord.yml - Testowy Workflow

name:  Discord Notifier Test (Manual/Tag)

on:
  push:
    tags:
      - 'test-*' # Uruchom na tag, np. test-success-1
  workflow_dispatch: # Opcjonalnie: Uruchomienie ręczne z UI GitHub Actions

jobs:
  # Zadanie A: Symulacja Sukcesu
  simulate_success:
    name: Simulating Successful Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Run a successful command
        run: echo "Deployment process OK!"

  # Zadanie B: Symulacja Porażki
  simulate_failure:
    name: Simulating Failed Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Run a command that will fail
        run: exit 1 # To celowo spowoduje błąd

  # Wywołanie Notifiera dla SUKCESU
  notify_success:
    name: Success Notification
    runs-on: ubuntu-latest
    needs: simulate_success # Czekaj na 'simulate_success'
    if: success() && always() # Wysłane, jeśli 'simulate_success' ZAKOŃCZYŁ SIĘ SUKCESEM
    uses: ./.github/workflows/discord_notifier.yml
    with:
      status: success 
      environment: TEST-SUCCESS
      commit_sha: ${{ github.sha }}
      actor: ${{ github.actor }}
    secrets:
      webhook_id: ${{ secrets.DEPLOY_WEBHOOK_ID }}
      webhook_token: ${{ secrets.DEPLOY_WEBHOOK_TOKEN }}
      
  # Wywołanie Notifiera dla BŁĘDU
  notify_failure:
    name: Failure Notification
    runs-on: ubuntu-latest
    needs: simulate_failure # Czekaj na 'simulate_failure'
    if: failure() && always() # Wysłane, jeśli 'simulate_failure' ZAKOŃCZYŁ SIĘ BŁĘDEM
    uses: ./.github/workflows/discord_notifier.yml
    with:
      status: failure
      environment: TEST-FAILURE
      commit_sha: ${{ github.sha }}
      actor: ${{ github.actor }}
    secrets:
      webhook_id: ${{ secrets.DEPLOY_WEBHOOK_ID }}
      webhook_token: ${{ secrets.DEPLOY_WEBHOOK_TOKEN }}