# .github/workflows/test_discord.yml - Workflow do testowania notifiera

name: Discord Notifier Test (Manual/Tag)

on:
  # Pozwala na ręczne uruchomienie z zakładki "Actions" na GitHubie
  workflow_dispatch:

  # Uruchamia się po wypchnięciu taga, który zaczyna się od "test-"
  push:
    tags:
      - 'test-*'

jobs:
  # Zadanie A: Symulacja sukcesu
  simulate_success:
    name: Simulating Successful Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Run a successful command
        run: echo "Deployment process OK!"

  # Zadanie B: Symulacja porażki
  simulate_failure:
    name: Simulating Failed Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Run a command that will fail
        run: exit 1 # To celowo spowoduje błąd

  # Wywołanie Notifiera dla SUKCESU
  notify_success:
    name: Success Notification
    needs: simulate_success
    runs-on: ubuntu-latest
    if: success()
    uses: ./.github/workflows/discord_notifier.yml
    with:
      status: success
      environment: TEST-SUCCESS
      commit_sha: ${{ github.sha }}
      actor: ${{ github.actor }}
    secrets:
      webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}

  # Wywołanie Notifiera dla BŁĘDU
  notify_failure:
    name: Failure Notification
    needs: simulate_failure
    runs-on: ubuntu-latest
    if: failure()
    uses: ./.github/workflows/discord_notifier.yml
    with:
      status: failure
      environment: TEST-FAILURE
      commit_sha: ${{ github.sha }}
      actor: ${{ github.actor }}
    secrets:
      webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}