# .github/workflows/test_discord.yml - Test Discord Notifier

name: 🧪 Discord Notifier Test

on:
  # Ręczne uruchomienie z zakładki Actions
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Test type to run'
        required: true
        default: 'both'
        type: choice
        options:
          - both
          - success
          - failure

  # Automatyczne uruchomienie przy push taga test-*
  push:
    tags:
      - 'test-*'

jobs:
  # ===================================================================
  # JOB 1: Symulacja SUKCESU
  # ===================================================================
  simulate_success:
    name: ✅ Simulating Successful Job
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'success' || github.event.inputs.test_type == 'both' || github.event_name == 'push'
    timeout-minutes: 2

    steps:
      - name: 🎭 Mock successful operation
        run: |
          echo "==================================="
          echo "🚀 Starting deployment simulation..."
          echo "==================================="
          sleep 3

          echo "✅ Database connection: OK"
          sleep 2

          echo "✅ Services health check: OK"
          sleep 2

          echo "✅ Deployment process: OK"
          sleep 2

          echo "==================================="
          echo "🎉 Deployment completed successfully!"
          echo "==================================="

  # ===================================================================
  # JOB 2: Symulacja PORAŻKI
  # ===================================================================
  simulate_failure:
    name: ❌ Simulating Failed Job
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'failure' || github.event.inputs.test_type == 'both' || github.event_name == 'push'
    timeout-minutes: 2

    steps:
      - name: 🎭 Mock failed operation
        run: |
          echo "==================================="
          echo "🚀 Starting deployment simulation..."
          echo "==================================="
          sleep 3

          echo "✅ Database connection: OK"
          sleep 2

          echo "❌ Services health check: FAILED"
          echo "Error: Connection timeout to service 'api-gateway'"
          sleep 2

          echo "==================================="
          echo "🚨 Deployment FAILED!"
          echo "==================================="
          exit 1  # To spowoduje błąd

  # ===================================================================
  # JOB 3: Powiadomienie o SUKCESIE
  # ===================================================================
  notify_success:
    name: 📢 Success Notification
    # ❌ NIE DODAWAJ runs-on tutaj!
    needs: simulate_success
    if: success() && (github.event.inputs.test_type == 'success' || github.event.inputs.test_type == 'both' || github.event_name == 'push')
    uses: ./.github/workflows/discord_notifier.yml
    with:
      status: success
      environment: TEST-SUCCESS
      commit_sha: ${{ github.sha }}
      actor: ${{ github.actor }}
    secrets:
      webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}

  # ===================================================================
  # JOB 4: Powiadomienie o PORAŻCE
  # ===================================================================
  notify_failure:
    name: 📢 Failure Notification
    # ❌ NIE DODAWAJ runs-on tutaj!
    needs: simulate_failure
    if: failure() && (github.event.inputs.test_type == 'failure' || github.event.inputs.test_type == 'both' || github.event_name == 'push')
    uses: ./.github/workflows/discord_notifier.yml
    with:
      status: failure
      environment: TEST-FAILURE
      commit_sha: ${{ github.sha }}
      actor: ${{ github.actor }}
    secrets:
      webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}

  # ===================================================================
  # JOB 5: Podsumowanie testu
  # ===================================================================
  test_summary:
    name: 📊 Test Summary
    runs-on: ubuntu-latest
    needs: [notify_success, notify_failure]
    if: always()

    steps:
      - name: 📋 Display results
        run: |
          echo "==================================="
          echo "🧪 Discord Notifier Test Summary"
          echo "==================================="
          echo ""
          echo "Test Type: ${{ github.event.inputs.test_type || 'both (auto)' }}"
          echo "Triggered by: ${{ github.actor }}"
          echo ""
          echo "Results:"
          echo "  - Success notification: ${{ needs.notify_success.result || 'skipped' }}"
          echo "  - Failure notification: ${{ needs.notify_failure.result || 'skipped' }}"
          echo ""
          echo "✅ Check your Discord channel for notifications!"
          echo "==================================="
